#!/bin/bash

echo "Resetting Network Settings"

networksetup listallnetworkservices|grep -v "*"|while read device
do
  echo "$device"
  sudo networksetup -setsocksfirewallproxy "$device" empty
  sudo networksetup -setsocksfirewallproxystate "$device" off
done
