#!/bin/bash

echo "Setting up Socks Network"

networksetup listallnetworkservices|grep -v "*"|while read device
do
  echo "$device"
  sudo networksetup -setsocksfirewallproxy "$device" localhost 1080
done

